apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AkyshBaymuhammedov/ms-infrastructure.git
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
