apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: master-ingress
  annotations:
    nginx.org/mergeable-ingress-type: 'master'
spec:
  ingressClassName: nginx
  rules:
    - host: akysh-micro-assignment.westeurope.cloudapp.azure.com