apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/bitcoin-app-ns.yaml
  - namespaces/nginx-ingress-ns.yaml
  - namespaces/simple-webserver-ns.yaml
  - ingress-resources/master-ingress.yaml