name: Infrastructure Deployment

on:
  workflow_dispatch:

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.9.0

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aks-engine
        run: |
          chmod 700 ./aks-engine/get-akse.sh && \
          ./aks-engine/get-akse.sh

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy cluster
        run: aks-engine deploy --dns-prefix ${{ secrets.RESOURCE_GROUP }} --resource-group ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.REGION }} --api-model ${GITHUB_WORKSPACE}/infrastructure/kubernetes.json --auto-suffix --subscription-id ${{ secrets.SUBSCRIPTION_ID }}

      - name: Retrieve path to kubeconfig
        run: echo "KUBECONFIG_PATH=$(pwd)/$(find _output -name kubeconfig.westeurope.json)" >> $GITHUB_ENV

      - name: Upload kubeconfig to Azure Key Vault
        run: |
          cat ${{ env.KUBECONFIG_PATH }} | base64 > KubeConfigInBase64 && \
          az keyvault secret set --vault-name ${{ secrets.KEY_VAULT }} --name kubeconfig-westeurope --disabled false --value @KubeConfigInBase64 && \
          rm KubeConfigInBase64

  configure-cluster:
    needs: deploy-cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Get kubeconfig from Azure Key Vault
        run: |
          az keyvault secret show --vault-name ${{ secrets.KEY_VAULT }} --name kubeconfig-westeurope --query value -o tsv | base64 --decode > kubeconfig-westeurope.json && \
          echo "KUBECONFIG=$(cat kubeconfig-westeurope.json | tr -d " \t\n\r")" >> $GITHUB_ENV

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{ env.KUBECONFIG }}

      - name: Wait for kube api server to be ready
        run: |
          chmod 700 ./wait_4_deploy.sh && \
          sleep 1m && ./wait_4_deploy.sh component=kube-apiserver kube-system kube-apiserver
        
      - name: Deploy ArgoCD
        run: |
          kubectl create ns argocd && \
          kubectl apply -n argocd -f ./argocd/install.yaml

      - name: Deploy manifests
        run: kubectl apply -f ./argocd/manifests-app.yaml

      - name: Deploy nginx ingress
        run: kubectl apply -f ./argocd/nginx-ingress/nginx-ingress-app.yaml

  configure-dns:
    needs: configure-cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Get kubeconfig from Azure Key Vault
        run: |
          az keyvault secret show --vault-name ${{ secrets.KEY_VAULT }} --name kubeconfig-westeurope --query value -o tsv | base64 --decode > kubeconfig-westeurope.json && \
          echo "KUBECONFIG=$(cat kubeconfig-westeurope.json | tr -d " \t\n\r")" >> $GITHUB_ENV

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{ env.KUBECONFIG }}

      - name: Wait for nginx-ingress
        run: |
          chmod 700 ./wait_4_deploy.sh && \
          ./wait_4_deploy.sh app=nginx-ingress-nginx-ingress nginx-ingress nginx-ingress

      - name: Set DNS label
        run: |
          PUBLIC_IP_NAME=$(az network public-ip list --resource-group ${{ secrets.RESOURCE_GROUP }} --query "[?starts_with(name, 'akysh-micro-assignment')].name" -o json | jq -r '.[0]') && \
          az network public-ip update -g ${{ secrets.RESOURCE_GROUP }} -n $PUBLIC_IP_NAME --dns-name ${{ secrets.RESOURCE_GROUP }} --allocation-method Static

  deploy-apps:
    needs: configure-dns
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Get kubeconfig from Azure Key Vault
        run: |
          az keyvault secret show --vault-name ${{ secrets.KEY_VAULT }} --name kubeconfig-westeurope --query value -o tsv | base64 --decode > kubeconfig-westeurope.json && \
          echo "KUBECONFIG=$(cat kubeconfig-westeurope.json | tr -d " \t\n\r")" >> $GITHUB_ENV

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{ env.KUBECONFIG }}

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: Helm login
        run: helm registry login ${{ secrets.ACR_REGISTRY }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

      - name: Check if required manifests were reconciled
        run: |
          chmod 700 ./wait_4_ns.sh && \
          ./wait_4_ns.sh bitcoin-app && ./wait_4_ns.sh simple-webserver

      - name: Deploy bitcoin-app
        run: helm upgrade --install bitcoin-app oci://${{ secrets.ACR_REGISTRY }}.azurecr.io/helm/bitcoin-app-helm -n bitcoin-app

      - name: Deploy simple-webserver
        run: helm upgrade --install simple-webserver oci://${{ secrets.ACR_REGISTRY }}.azurecr.io/helm/simple-webserver-helm -n simple-webserver
