name: Infrastructure Deployment

on:
  workflow_dispatch:

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aks-engine
        run: |
          chmod 700 ./aks-engine/get-akse.sh && \
          ./aks-engine/get-akse.sh

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy cluster
        run: aks-engine deploy --dns-prefix ${{ secrets.RESOURCE_GROUP }} --resource-group ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.REGION }} --api-model ${GITHUB_WORKSPACE}/infrastructure/kubernetes.json --auto-suffix --subscription-id ${{ secrets.SUBSCRIPTION_ID }}

      - name: Retrieve path to kubeconfig
        run: echo "KUBECONFIG_PATH=$(pwd)/$(find _output -name kubeconfig.westeurope.json)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: kubeconfig
          path: ${{ env.KUBECONFIG_PATH }}

  deploy-argocd:
    needs: deploy-cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: kubeconfig

      - name: Set kubeconfig
        run: echo "KUBECONFIG=$(cat kubeconfig.westeurope.json)" >> $GITHUB_ENV

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{ env.KUBECONFIG }}

      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd && \
          kubectl apply -n argocd -f ./argocd/install.yaml

      - name: Install Manifests app
        run: kubectl apply -f ./argocd/manifests-app.yaml
