name: Infrastructure Deployment

on:
  workflow_dispatch:

jobs:
  aks-engine-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aks-engine
        run: |
          curl -o get-akse.sh https://raw.githubusercontent.com/Azure/aks-engine/master/scripts/get-akse.sh && \
          chmod 700 get-akse.sh && \
          ./get-akse.sh

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy cluster
        run: aks-engine deploy --dns-prefix ${{ secrets.RESOURCE_GROUP }} --resource-group ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.REGION }} --api-model ${GITHUB_WORKSPACE}/infrastructure/kubernetes.json --auto-suffix --subscription-id ${{ secrets.SUBSCRIPTION_ID }}
